[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

# Change the `name` of this constraint to be the import path of the upstream
# Terraform provider, and set the `version` to be the tag name of the release
# you wish to pin to.
#
# If it is necessary to fork the provider, set the `name` to the canonical import
# path (i.e. github.com/terraform-providers/terraform-provider-x), and set the
# `source` to the fork address. Then set the `branch` to `pulumi-master` in the
# fork, and ensure `version` is not set.
[[constraint]]
  version = "v1.6.0"
  name = "github.com/terraform-providers/terraform-provider-packet"

  [constraint.metadata]
    gomod-override = true
    gomod-exclude-prefixes = [
      "github.com/golang/protobuf",
    ]


# NOTE: this Gopkg.toml file was constructed using gomod-override

[[override]]
  name = "github.com/agext/levenshtein"
  version = "=v1.2.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-cidr"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-dump"
  revision = "23540a00eaa318ee47d517dd7653fc81156a3e7e"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-textseg"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/armon/go-radix"
  revision = "7fddfc383310abc091d79a27f116d30cf0424032"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.15.78"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/bgentry/speakeasy"
  version = "=v0.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/blang/semver"
  version = "=v3.5.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/bsm/go-vlq"
  revision = "ec6e8d4f5f4ec0f6e808ffc7f4dcc7516d4d7d49"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/cheggaaa/pb"
  version = "=v1.0.27"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/davecgh/go-spew"
  version = "=v1.1.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/fatih/color"
  version = "=v1.7.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/fsnotify/fsnotify"
  version = "=v1.4.7"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/go-test/deep"
  version = "=v1.0.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/google/go-cmp"
  version = "=v0.2.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/errwrap"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  version = "=v0.5.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-getter"
  version = "=v1.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-hclog"
  version = "=v0.7.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-multierror"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "3f118e8ee104b6f22aeb12453fab56aed1356186"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-safetemp"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-uuid"
  version = "=v1.0.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/go-version"
  version = "=v1.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "7e26f2f3461267613602a534185654331d113c60"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "97b3a9cdfa9349086cfad7ea2fe3165bfe3cbf63"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/logutils"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "=v0.11.11"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "3520598351bb3500a49ae9563f5539666ae0a27c"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/hpcloud/tail"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/jessevdk/go-flags"
  version = "=v1.4.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "0b12d6b521d83fc7f755e7cfc1b1fbdd35a01a74"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/kr/pretty"
  version = "=v0.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/kr/pty"
  version = "=v1.1.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/kr/text"
  version = "=v0.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/kylelemons/godebug"
  revision = "d65d576e9348f5982d7f6d83682b694e731a45c6"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mattn/go-colorable"
  version = "=v0.0.9"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mattn/go-isatty"
  version = "=v0.0.4"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mattn/go-runewidth"
  version = "=v0.0.4"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/cli"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/copystructure"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/go-homedir"
  version = "=v1.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/go-testing-interface"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/hashstructure"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/mapstructure"
  version = "=v1.1.2"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/oklog/run"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/onsi/ginkgo"
  version = "=v1.7.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/onsi/gomega"
  version = "=v1.4.3"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/packethost/packngo"
  revision = "c53c0868b5e0f9652ebcf7d679132f74695d3ffb"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/pmezard/go-difflib"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/posener/complete"
  version = "=v1.1.1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/sergi/go-diff"
  version = "=v1.0.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/spf13/pflag"
  version = "=v1.0.2"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/stretchr/objx"
  version = "=v0.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/stretchr/testify"
  version = "=v1.3.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/ulikunitz/xz"
  version = "=v0.5.5"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/vmihailenco/msgpack"
  version = "=v3.3.3"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "19dda139b164a5503de2051225fa6b94f5d39e05"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/crypto"
  revision = "31a38585487a4b1fd6ff4f8f3db26f1fb296ac82"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/net"
  revision = "c95aed5357e77a4bf7d3955c46740000a17adee1"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/sync"
  revision = "37e7f081c4d4c64e13b10787722085407fe5d15f"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/sys"
  revision = "d0b11bdaac8adb652bff00e49bcacf992835621a"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "golang.org/x/text"
  version = "=v0.3.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "google.golang.org/appengine"
  version = "=v1.1.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "google.golang.org/genproto"
  revision = "c66870c02cf823ceb633bcd05be3c7cda29976f4"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "google.golang.org/grpc"
  version = "=v1.14.0"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "gopkg.in/check.v1"
  revision = "788fd78401277ebd861206a03c884797c6ec5541"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "=v1.0.27"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  version = "=v1.4.7"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "gopkg.in/tomb.v1"
  revision = "dd632973f1e7218eb1089048e0798ec9ae7dceb8"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "=v2.2.2"
  [override.metadata]
    gomod-overridden=true

[[override]]
  name = "howett.net/plist"
  revision = "591f970eefbbeb04d7b37f334a0c4c3256e32876"
  [override.metadata]
    gomod-overridden=true
